### ISSUE TITLE
pythonmodulo is wrong on negative number

### ISSUE THREAD

**Issue by tamptus** [minetest/minetestmapper#100]
pythonmodulo in include/db.h

pythonmodulo(-4096,4096) return 4096
but should be 0
possible correction:
change: return mod - ((-i) % mod);
to: return (mod - ((-i) % mod)) % mod);

Tamptus

**Comment by sfan5** [comment]
Could be, but it works exactly like this in Minetest:
https://github.com/minetest/minetest/blob/bc336480e6317fec4eea03b055bcf9602ff633d7/src/database/database.cpp#L41-L48

We can't apply any fixes or it would no longer work.
