### ISSUE TITLE
Mapper producing a white image

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest/minetestmapper#11]
Ok, so not sure how to explain this but il do my best.

Basically running the mapper is producing a plain white image almost like the map has never been explored.

At first i thought it may have been a colors.txt issue with my custom file. so i removed it and reverted back to the default but it still happened. after that i removed the mapper entirely, re downloaded and recompiled it, after running it it produced the same white image as before. 

I have since tried mireq's minetest-mapper-cpp and it works perfectly but s we know doesn't look as good as this one.

**Comment by sfan5** [comment]
Please reopen when you find a way to reproduce this.
