### ISSUE TITLE
Selectively exclude specific nodes

### ISSUE THREAD

**Issue by gangelop** [minetest/minetestmapper#13]
Hello!

I'm using `minetestmapper` to generate the [map for Liberty Land](http://www.ayntest.net/pages/map.html). We wanted to hide nyancats so as to not give away their locations, so @donat-b simply removed the two color definitions from `colors.txt`. I was thinking that this might be useful as a command-line option, something like

``` bash
./minetestmapper \
--exclude "default:nyancat" \
--exclude "default:nyancat_rainbow" \
-i world/ -o map.png
```

**Comment by fluxionary** [comment]
@gangelop I have no idea what the state of this project was 6 years ago, but currently, you can omit the nyans from `colors.txt` and then use the `--drawalpha` argument, and they will be treated as transparent. Alternatively, you could set the color for the nyan in `colors.txt` to be the same color as stone (or whatever your world is mostly built from)

**Comment by gangelop** [comment]
Haven't touched minetest for some years now. Thanks for the reply though :)
