### ISSUE TITLE
Mapper should warn about huge image dimensions

### ISSUE THREAD

**Issue by sirken** [minetest/minetestmapper#14]
Mint 13 64-bit
Minetest 0.4.10-71...

The mapping was working fine after creating a new world. Then, the maps stopped generating. I think what triggered it was teleporting ~12000x10000 meters to another section of the world which was previously undiscovered.

I tried minetestmapper.py and it generated the map ok. So, I ran gdb but all I got was this, which is probably not helpful. How else to troubleshoot?
```
(gdb) run
Starting program: /home/test/minetest/util/minetestmapper -i /home/test/minetest/worlds/world/ -o /home/test/minetest-map.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)
```

**Comment by ShadowNinja** [comment]
@sfan5: The mapper should at least warm the user about big maps instead of just getting OOM-killed.
