### ISSUE TITLE
Unknown nodes (colors.txt needs re-gen)

### ISSUE THREAD

**Issue by anton-tsyganenko** [minetest/minetestmapper#15]
Minetestmapper doesn't work with pine trees (default) and iron bars (xpanes), that are in vanilla minetest_game.

**Comment by paramat** [comment]
Many new nodes need adding to 'colors.txt', here's a quick list of my own additions for 0.4.13 stable:

default:river_water_source 39 90 106 128 224
default:river_water_flowing 39 90 106 128 224
default:acacia_leaves 47 80 41
default:acacia_tree 234 207 156
default:dirt_with_dry_grass 147 119 71
default:dry_grass_1 188 160 0
default:dry_grass_2 188 160 0
default:dry_grass_3 188 160 0
default:dry_grass_4 188 160 0
default:dry_grass_5 188 160 0

Here are the pine nodes, pinetree and pinewood have been renamed for 0.4.13:

default:pine_tree 95 85 73
default:pine_wood 226 191 138
default:pine_needles 11 30 19
default:pine_sapling 3 55 20

**Comment by Kevin-Mok** [comment]
Same issue with `fireflies:firefly` and `fireflies:hidden_firefly`.

**Comment by sfan5** [comment]
Fireflies are intentionally hidden, though maybe the warning message shouldn't appear for them.
