### ISSUE TITLE
Mapper fails when any colour command is used

### ISSUE THREAD

**Issue by paramat** [minetest/minetestmapper#17]
When i run the following command or add any colour option the mapper fails and the error message below appears.

$ ./minetestmapper -i ~/minetestf/gitmods/minetest/worlds/m2/ -o ~/m2map.png --bgcolor #000000 

./minetestmapper: option '--bgcolor' requires an argument

**Comment by Rogier-5** [comment]
The shell interprets '#' as the start of a 
comment, and ignores it and the remainder 
of the line. Enclose the color in quotes, and 
it should work:

$ ./minetestmapper -i 
~/minetestf/gitmods/minetest/worlds/m2/ -o 
~/m2map.png --bgcolor '#000000'

**Comment by paramat** [comment]
It works, thanks, closing.
