### ISSUE TITLE
Redis supported ? No map generation

### ISSUE THREAD

**Issue by fgrosswig** [minetest/minetestmapper#19]
After we managed to compile the mapper with redis support (told us so) we run the mapper with the backend redis switch and waited about over an hour. The result was no map where generated just a an png file of an size about 176kbyte which couldn't be right cuz our map is about 4gigabyte at least. So how may we are able to elaborate this into detail where the issue resides to generate the map out of redis yet. 

Tia

**Comment by Rogier-5** [comment]
I don't know if your map covers a particularly large area ?

If you are mapping a large area, the mapper requires a huge amount of memory. Maybe your computer was swapping all the time ? You could try mapping a small area to begin with, and proceed from there. And do monitor memory and swap usage while you're mapping...

If you are running the redis server on the same machine, do consider that redis may also need a huge amount of memory: as far as I remember, it keeps its *entire* database loaded in memory.

**Comment by HybridDog** [comment]
Would it work faster if you generate one png for each mapchunk and combine them to a big png file?

**Comment by est31** [comment]
Btw, big png files are inferior. You have limited zoom capabilities and you have to load the whole map. I've written [leaftest](https://github.com/est31/leaftest) to map into small chunks and then generate a zoomable, sloppy map.

**Comment by Rogier-5** [comment]
> Would it work faster if you generate one png for each mapchunk and
> combine them to a big png file?

It would definitely use much less memory. If that means a huge amount of 
swapping is avoided, then it might be faster. However, a map chunk is small, and 
if the map were 64kx64k for instance (hypothetically; as minetestmapper (or 
rather libgd, which minetestmapper uses) can't handle images that size), you'd 
still have to generate approx 16k PNGs. That's a lot, and the extra overhead of 
starting minetestmapper every time might annihilate your savings...

So, I'd recommend generating a smaller number of map sections, e.g. 8kx8k 
pixels each. That would reduce memory usage by almost a factor 64. The 
computational effort required to combine them would probably also be much 
less than with images of 80x80 pixels (= 1 chunk).

The most minetestmapper can generate (AFAIK) is approx. 46kx46x, on 64-bit 
architectures. On 32-bit architectures, 24kx24k maps are the approximate limit. 
Note also that many 32-bit viewing applications are not designed for huge 
images, and will fail to load such maps, as they can't fit them into memory. A 
20kx20k map for instance would consume at the very least 400M of memory, but 
a figure of 800M or 1.2G is more realistic, and it might even be 1.6G...).

See also this: 
https://forum.minetest.net/viewtopic.php?f=14&t=2896&sid=432191b8e0fa6a6c
61d62b5b2a38d9de&start=125#p170875 message by est31. His script might be 
of use.

**Comment by fgrosswig** [comment]
We are using zoomify to split huge map png into zoom able maps. 

The issue due to the map generating issue we can't tell yet. We know that redis moves the whole map into RAM that's why we use ssd and 8GB server to held the map into the ram. I got drawed the map one time but can't repeat it. No idea what's the issue here because due the technics the map generation should work flawlessly beside the server still runs.

**Comment by Rogier-5** [comment]
> The issue due to the map generating issue we can't tell yet. 
We know
> that redis moves the whole map into RAM that's why we use 
ssd and
> 8GB server to held the map into the ram. I got drawed the 
map one
> time but can't repeat it. No idea what's the issue here 
because due
> the technics the map generation should work flawlessly 
beside the
> server still runs.

Your world's dimensions might have increased since ?

What *are* the actual dimensions of your world anyway ?

**Comment by fgrosswig** [comment]
Ugh how to retrieve the size?

**Comment by Rogier-5** [comment]
Depends...

Assuming you're using the standard version of minetestmapper:

In Tilegenerator.cpp, in TileGenerator::loadBlocks, just before m_positions.sort(), add a line to print m_xMin, m_xMax, m_zMin and m_zMax. Something like:
```
    std::cout << "X: " << m_xMin*16 << " ... " << m_xMax * 16 + 15 << " (size: " << (m_xMax - m_xMin + 1)*16 << ")" << std::endl; 
    std::cout << "Z: " << m_zMin*16 << " ... " << m_zMax * 16 + 15 << " (size: " << (m_zMax - m_zMin + 1)*16 << ")" << std::endl;
```
This reports the min and max *map* coordinates, so don't use --geometry if you want to know the total world size.
(disclaimer: untested code)

Or you can query redis for a list of keys, decode the coordinates, and compute the min and max yourself...

If you're using my version of minetestmapper, use the option --verbose=1 or --verbose=2.

**Comment by fgrosswig** [comment]
ok no need to know the whole size, guess we add this to the command --geometry -3000:-3000+6000+6000. which reduces the map potentially but it does not need to bee bigger than that.

**Comment by HybridDog** [comment]
Does onomatopoeia support redis?
https://github.com/Zeg9/onomatopoeia

**Comment by Rogier-5** [comment]
@fgrosswig: I would be surprised if a 6kx6k map gave you any memory-related problems.

@HybridDog: 
> Does onomatopoeia support redis?

From a superficial examination of the source: no

> ls it possible to generate a map using e.g. every 10th x and z coordinate?

Not using the default version of minetestmapper. Some other mappers do support some kind of scaling. Minetestmapper-numpy does (reportedly), and my version of minetestmapper does as well.

**Comment by fgrosswig** [comment]
we are not reaching any memory limited problems. we just cannot create the map thats all ;-)

**Comment by Rogier-5** [comment]
Strange. An hour seems like a loooong time for such a small image....
A 6000x6000 image could be more or less that size (I just generated one of 150k), but only if it is very compressible. E.g. just one plain color...

What is the output of `file map-01072015-1920.png` ? (reports the image size)

What does the generated image look like ?

What is the full command-line - what options did you use ?

Do you get any error (or other) messages ?

Is the colors.txt file OK ? Are you using the file that came with minetestmapper, or a custom file ? Do you get any message about 'unknown nodes' ?
Bad colors definitions could cause all (or most) nodes to be invisble, which would cause the image to be just the background color, extremely compressible as a result, and it would also explain an excessively long running time.

How long does it take to generate a small map ? say 100x100 pixels.

**Comment by fgrosswig** [comment]
>PNG image data, 6016 x 6016, 8-bit/color RGB, non-interlaced

The picture is white no area rendered.

>minetestmapper --backend redis --geometry -3000:-3000+6000+6000 -i /home/minetest/ftp/world -o /home/minetest/ftp/screens/map-DATE

we use the out of the box colors.txt - yes we do have a lot of unknown nodes at the mapper but this wasnt a problem yet to get the map drawed (prior on sqlite and sometimes on redis)

the 100x100 takes about 30 seconds
![map-100px](https://cloud.githubusercontent.com/assets/803345/8471712/61951be6-209b-11e5-8ee8-9d405e6e570f.png)

**Comment by Rogier-5** [comment]
>>PNG image data, 6016 x 6016, 8-bit/color RGB, non-interlaced

>The picture is white no area rendered.

So, it seems to be some problem with the colors indeed: somehow all pixels ended up transparent or invisible.
But then both small and lage maps should be affected, so I can't explain why a 100x100 map is OK...

Are you generating the 100x100 map in the same working directory as the 6000x6000 map ? If you aren't, then minetestmapper might accidentally be using a different colors.txt file...

Try using --min-y and --max-y to limit what is being mapped. Set them to -20 and 50 for example. I expect that that will at least improve the mapping speed on the 6000x6000 map.

As the 100x100 map is OK, could you try several increasing map sizes, to see at what size the problem starts ?

If possible, could you try mapping with my version of minetestmapper (https://github.com/Rogier-5/minetest-mapper-cpp) to see whether it has the same problem ? When you do, use the options '--verbose=2' and '--verbose-search-colors', and let me know the information that it reports.

BTW: I haven't managed to reproduce the problem myself.

**Comment by sfan5** [comment]
I can't reproduce the problem here either, minetestmapper successfully generates a map when using redis.

**Comment by fgrosswig** [comment]
i doubt there is not a problem with the redis integration - but with the area (size of map) itself? ill try later on this settings to see where it leads. making 10 samples will spend some time. O_o
