### ISSUE TITLE
Feature Request: Show online users on generated map.

### ISSUE THREAD

**Issue by aerth** [minetest/minetestmapper#21]
Could be large dots or circles...

**Comment by Rogier-5** [comment]
--drawplayers shows all players, but I assume you knew that, and it's not what you are asking for ?

**Comment by sfan5** [comment]
This is not possible with some type of integration with minetestserver, online players are not stored in the database or anywhere.

**Comment by aerth** [comment]
--drawplayers did exactly what i was looking for.  thanks

**Comment by aerth** [comment]
All users, not online users. but it works
