### ISSUE TITLE
README unclear on geometry

### ISSUE THREAD

**Issue by paramat** [minetest/minetestmapper#22]
--geometry -800:-800+1600+1600
First i assumed a typo because i was assuming this to be minp maxp, the colon seemed wrongly placed. Then i stumbled across the error message in terminal:
--geometry x:y+w+h
Makes it clearer, but some people wonder if x:y is the centre.
'-800:-800+1600+1600' seems to imply x:y is the minp and i am now assuming this.

**Comment by sfan5** [comment]
> Makes it clearer, but some people wonder if x:y is the centre.

X and Y coords are pretty much always the top-left corner of an area.
IMO that's understandable without clarifying the documentation

**Comment by PilzAdam** [comment]
Maybe a bunch of different options can be supplied, to make everyone happy:
```
--minp -800:-800
--minx -800 --miny -800
--center 0:0
--dimension 1600:600
--width 1600
--height 1600
--maxp 800:800
```

**Comment by HybridDog** [comment]
it wouldn't make me happy

**Comment by ShadowNinja** [comment]
I think a minp/maxp based command would be less confusing.  I found the syntax a little confusing at first too.

**Comment by HybridDog** [comment]
maybe the geometry syntax is made similar to the one of imagemagick

**Comment by paramat** [comment]
All iask for is that the README includes the format x:y+w+h and notes that x:y is the lower left corner, w and h the width and height.
