### ISSUE TITLE
Enabling drawalpha will cause segfault if seabed is not generated

### ISSUE THREAD

**Issue by paramat** [minetest/minetestmapper#24]
The mapper crashed, running it in gdb i found the problem was in renderMapBlockBottom.
Seeing the drawalpha option there i disabled it and this fixed the problem.
The map showed a world where parts of the seabed had not been generated yet.
As far as i can remember i then generated the seabed and drawalpha then worked.
I suspect the problem is that drawalpha needs a seabed level, if one is not found there should be a fallback value to avoid a crash.
Seabed not generating is common in any mapgen with deep ocean, such as mgv5, or when the player has been flying high over a map.

**Comment by sfan5** [comment]
Can't reproduce.
