### ISSUE TITLE
Minetest-mapper crash using --geometry x:y+w+h

### ISSUE THREAD

**Issue by dalmemail** [minetest/minetestmapper#25]
I am using minetest-mapper to make a map of a really big world so I tried to use --geometry option. If I do: $ ./minetestmapper --geometry 0:0+500+500 -i ../ -o test.png
It works, but if I change "0:0" to "-1600:3300" it says: "segmentation fault ('core')"

If I tried to make the full map it works, but it makes a 60MB PNG file, so I want to use --geometry option.

**Comment by sfan5** [comment]
Can you run minetestmapper in gdb and post a backtrace?
(preferably with a debug build too)

**Comment by HybridDog** [comment]
l think leaftest is suitable for big maps: https://github.com/est31/leaftest

**Comment by est31** [comment]
+1 that, leaftest was designed with constrained RAM in mind.
