### ISSUE TITLE
Conflicting license information?

### ISSUE THREAD

**Issue by thePalindrome** [minetest/minetestmapper#26]
File LICENCE specifies LGPL 2.1+, but COPYING as well as the metadata for AUTHORS says it's BSD.

Is this dual licensed, or am I missing something?

**Comment by est31** [comment]
Well there is commit 191f9180de7ebcd11923e3b23d56935e07a0d4ce from 2012 which adds the LGPL license, and 7e3e0a067c3a85f69d63f0849a1c621d45419ad9 from 2014 which adds the BSD license... I don't really know, I assume its dual licensed if 7e3e0a067c3a85f69d63f0849a1c621d45419ad9 is legit, meaning that all contributors have agreed to it. But even if it is dual licensed, this should be pointed out.

Either way, this is really bad.

**Comment by ShadowNinja** [comment]
@sfan5: Was that commit mistaken?  It looks like this should be LGPL.
