### ISSUE TITLE
Currently unsuitable for installation

### ISSUE THREAD

**Issue by thePalindrome** [minetest/minetestmapper#27]
Firstly, there is no make install step to allow for a package manager to drop the files where they should be, but most importantly...

minetestmapper currently reads the colors.txt from the current working directory, as opposed to the program's directory.

This is problematic because an installation is meaningless if a colors.txt must be present in order to use the tool.

**Comment by est31** [comment]
Well colors.txt is supposed to be supplied by the user and not us.

**Comment by thePalindrome** [comment]
The issue I'm seeing is that whenever you make a map, you have to have a colors.txt present, which can make things rather tricky should you want to install it via a package manager.

**Comment by est31** [comment]
Well its one of the data you have to provide to the mapper. Perhaps its unfortunate that the mapper assumes an implied location, but still it can and should not be shipped with the mapper. Its something the user has to supply and maintain.

**Comment by thePalindrome** [comment]
Granted, I do know that minetestmapper is meant to have a user supplied colors.txt, but I would like to propose the following:

By default it will search for colors.txt in the program's directory (possibly some other default location) and then allow a -c or --config option to specify a separate one.

If it doesn't find a colors.txt in the program directory and -c has not been set, it should give an error stating that you require a colors.txt

The current behavior will spend the whole time generating a white image.

Should this be satisfactory, I will create a patch.

**Comment by fgrosswig** [comment]
Sounds like a plan

**Comment by est31** [comment]
@rogier-5 's fork calls it `--colors`, perhaps we should use that to not break compat.

**Comment by thePalindrome** [comment]
TO THE FUTURE:

I am creating a patch that will add a -c --colors option to specify colors.txt, with the default location being the program directory. minetestmapper will die should the observed colors.txt be non-existant.

TO THE PRESENT:
Any additions should be noted here

**Comment by est31** [comment]
Generally, if you want to package the minetest mapper, I suggest you to package rogier's fork atm, as it has more features and less bugs than this "official" one. This is unfortunate but true.

**Comment by thePalindrome** [comment]
So I would presume that rogier's fork will eventually merge into the "official" one?

**Comment by fgrosswig** [comment]
there was s colors.txt generator somewhere on here, why does a switch like --gen-color not pre-run to satisfy the lack of non existent file? For sure it has to merge and work together instead using all its own product

**Comment by thePalindrome** [comment]
Alright, updating to suggest generating a colors.txt if none is found.

**Comment by est31** [comment]
@thePalindrome well basically this mapper is not maintained, or kept at life support while the fork flourishes. About merging back, there have been some attempts at doing so but they all failed. I can't recall whom to blame on that.

The general situation on this is really a bit bad.

So if you do a PR to this mapper, make sure its compatible to the fork. This is at least my opinion.

**Comment by thePalindrome** [comment]
oof, I'll see what I can do then.

**Comment by sfan5** [comment]
>less bugs than this "official" one. This is unfortunate but true.

I'd like to hear about some more bugs if there are so many. Most of the currently filed issues are either 1) obscure, hard-to-reproduce issues or 2) segfaults that haven't been fixed (yet).

**Comment by Rogier-5** [comment]
My manual describing the search locations of my version of minetestmapper is [here](https://github.com/Rogier-5/minetest-mapper-cpp/blob/master/doc/manual.rst#colors-files-search-locations). My version handles the Unix/Linux case well, and hopefully the Windows case at least satisfactorily (and better in any case than the standard version of minetestmapper does - but I am open to suggestions for improvement). It looks for the colors file in different locations, including the world's directory. For compatibility with the standard version of minetestmapper, it will use a colors file present in the current working directory as a last resort, but it issues a warning message if it does.

Wrt to option names: my version uses `--colors` and `-C`. Lower case `-c` is already in use as an alias for `--max-y` in both versions of minetestmapper.
