### ISSUE TITLE
Water colour?

### ISSUE THREAD

**Issue by enkidu-smith** [minetest/minetestmapper#41]
When I make a map of my world the water surfaces are transparent, so the background colour shows through. This makes it very difficult in areas that are mostly water and not very explored. Is this a usage issue, or is it expected behaviour? The minetest and minetestmapper programs are recent downloads from github, compiled on my Ubuntu 16.10 system.

**Comment by est31** [comment]
I think you can set the color in your colors.txt file, but I may be mistaken. I think there is an option for it.

**Comment by sfan5** [comment]
Does minetestmapper complain about any unknown nodes when you run it?

**Comment by enkidu-smith** [comment]
No. There are no complaints about unknown nodes.

I have since downloaded and compiled the version by Rogier (
https://github.com/Rogier-5/minetest-mapper-cpp) and it works fine. I
didn't realise that there were several versions of the program and I'm now
unsure which was the version that I tried first. I believe that it was the
one linked to by the Wiki page (http://wiki.minetest.net/Minetestmapper)
which is your one on GitHub I believe.

Here's my command line:
/usr/local/games/minetest-master/util/minetestmapper -i
/root/.minetest/worlds/world --output /home/cliff/output_all.png
--draworigin --drawscale --drawplayers --colors
/usr/local/games/minetest-master/util/colors.txt --bgcolor #444444

Here's the only output:
Warning: The width or height of the image to be created exceeds 4096
pixels! (Dimensions: 4952x3432)

I didn't get that message originally, but my world has grown immensely!

I cannot recall exactly where I got the colors.txt file from. I can zip it
up and attach it to an email if you like or paste a 'grep' of particular
lines. Or you could send me a colors.txt that works for you?

Cheers,

Cliff

**Comment by sfan5** [comment]
It looks you were using the colors file included with minetest (aka the wrong one).

Try again without copying anything around like this:
```
git clone https://github.com/minetest/minetestmapper
cd minetestmapper
cmake . && make
./minetestmapper -i /root/.minetest/worlds/world -o /home/cliff/output_all.png
    --draworigin --drawscale --drawplayers --bgcolor #444444
```

**Comment by enkidu-smith** [comment]
No change.

Here is the compile output:
cliff@Ubuntu-16:~/minetestmapper$ cmake . && make
-- The CXX compiler identification is GNU 6.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- libgd library: /usr/lib/x86_64-linux-gnu/libgd.so
-- libgd headers: /usr/include
-- zlib library: /usr/lib/x86_64-linux-gnu/libz.so
-- zlib headers: /usr/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- sqlite3 library: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- sqlite3 headers: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cliff/minetestmapper
Scanning dependencies of target minetestmapper
[ 11%] Building CXX object
CMakeFiles/minetestmapper.dir/PixelAttributes.cpp.o
[ 22%] Building CXX object
CMakeFiles/minetestmapper.dir/PlayerAttributes.cpp.o
[ 33%] Building CXX object CMakeFiles/minetestmapper.dir/TileGenerator.cpp.o
[ 44%] Building CXX object
CMakeFiles/minetestmapper.dir/ZlibDecompressor.cpp.o
[ 55%] Building CXX object CMakeFiles/minetestmapper.dir/Image.cpp.o
[ 66%] Building CXX object CMakeFiles/minetestmapper.dir/mapper.cpp.o
[ 77%] Building CXX object CMakeFiles/minetestmapper.dir/util.cpp.o
[ 88%] Building CXX object CMakeFiles/minetestmapper.dir/db-sqlite3.cpp.o
[100%] Linking CXX executable minetestmapper
[100%] Built target minetestmapper

Here is the output of the run:
It does complain about  moreores:mineral_tin. My apologies. I recall that I
added the definitions for moreores to the colors.txt and that fixed that
issue. Does that make a difference? Also, I dropped the --bgcolor parameter
so water and unknown areas are white. Currently it runs as root, which I
must fix hence the sudo. The server is private but I was an adminlong
enough to know that that is NOT GOOD.

cliff@Ubuntu-16:~/minetestmapper$ sudo ./minetestmapper -i
/root/.minetest/worlds/world -o /home/cliff/output_all.png --draworigin
--drawscale --drawplayers
Warning: Falling back to using colors.txt from current directory.
Warning: The width or height of the image to be created exceeds 4096
pixels! (Dimensions: 4952x3432)
Unknown nodes:
moreores:mineral_tin

grepping the colors.txt for "water" produces this:

default:river_water_flowing 39 66 106 128 224
default:river_water_source 39 66 106 128 224
default:water_flowing 39 66 106 128 224
default:water_source 39 66 106 128 224
flowers:waterlily 102 158 61

Oh, and I use minetest_game on minetest running on a separate machine to
the client, but of course I run the mapper on the server.

Cheers,

Cliff

**Comment by sfan5** [comment]
Fuck, sorry for bothering you that long.
You're right this always happens and it's not your fault (i've reproduced it myself)

**Comment by enkidu-smith** [comment]
No worries!

Cheers,

Cliff

**Comment by enkidu-smith** [comment]
Confirming that I now have blue water! Sweet...

Cheers,

Cliff
