### ISSUE TITLE
Minetest mapper and 0.4.15

### ISSUE THREAD

**Issue by enkidu-smith** [minetest/minetestmapper#44]
I just upgraded from 0.4.14 to 0.4.15 and now Minetest Mapper doesn't work. It runs for a while then calls terminate as follows and dumps core:

`Warning: The width or height of the image to be created exceeds 4096 pixels! (Dimensions: 6392x9112)`
`terminate called after throwing an instance of 'ZlibDecompressor::DecompressError'`

I'm running Minetest on Ubuntu 16.10. Both 0.4.15 and the mapper prog were downloaded and compiled for this new release. I use "minetest_game" and a few mods. 

Is anyone else seeing this?

**Comment by sfan5** [comment]
It seems that there is a broken/invalid MapBlock in your map.

**Comment by enkidu-smith** [comment]
Thanks. So it's a coincidence that it broke when I upgraded Minetest? Do
you know if there is a way to find and fix/remove it, please? I can't see
anything in the forums or on the wiki.

Cheers,

Cliff

**Comment by enkidu-smith** [comment]
Hm, unless I am doing something silly there is a problem. 

I did the following:

1) Restored from backup. Didn't start the server.
2) Ran the mapper and all was OK.
3) Started the server.
4) Logged in, moved around, all seemed well.
5) Stopped the server.
6) Ran the mapper and had the same issue as above. 

Cheers,

Cliff

**Comment by sfan5** [comment]
Are you using `0.4.15` or `0.4.15-dev`? This is quite important difference.
If you use the -dev version you will need to recompile the mapper to include the commit from yesterday (21444d00c35dc6896ffc27af7da38d8a296178fd)

**Comment by enkidu-smith** [comment]
That works. My apologies, I must have picked up the -dev version of
Minetest at some stage.

Cheers,

Cliff
