### ISSUE TITLE
Here are new node entries for colors.txt

### ISSUE THREAD

**Issue by paramat** [minetest/minetestmapper#56]
Tested for contrast in environment and distinguishability from other nodes (where reasonably possible).
Stair inner and outer corners need adding for all stair nodes, a copypaste job i might do and paste here later.
```
# New
default:cave_ice 167 206 247
default:dirt_with_coniferous_litter 135 107 73
default:fern_1 126 173 74
default:fern_2 126 173 74
default:fern_3 126 173 74
default:marram_grass_1 84 138 91
default:marram_grass_2 84 138 91
default:marram_grass_3 84 138 91
default:sand_with_kelp 133 132 44
fireflies:firefly 255 234 0
fireflies:firefly_bottle 255 234 0
flowers:chrysanthemum_green 194 218 44
flowers:tulip_black 59 17 37
```
![newcolors2](https://user-images.githubusercontent.com/3686677/37871191-2db53de0-2fe0-11e8-9dda-c43f37940b27.png)

^ With water removed to see kelp

**Comment by sfan5** [comment]
`colors.txt` is auto-generated so I'd prefer to keep the amount of manual entries to a minimum.
Will check which color the algorithm comes up with.

**Comment by sfan5** [comment]
<pre>
default:cave_ice 167 206 247
default:dirt_with_coniferous_litter 107 88 68
default:fern_1 81 114 48
default:fern_2 86 118 50
default:fern_3 88 121 52
default:marram_grass_1 96 133 89
default:marram_grass_2 87 126 83
default:marram_grass_3 85 125 82
default:sand_with_kelp 214 207 158
fireflies:firefly_bottle 190 191 198
flowers:chrysanthemum_green 101 140 39
flowers:tulip_black 72 103 63
</pre>
(from a8f7b47)
With a few exceptions somewhat close to your suggestions.

**Comment by paramat** [comment]
Ah interesting, didn't realise you used automatic values, manual is sometimes better when auto doesn't make sense, for example black tulips have mostly green pixels but should be very dark purple, likewise for all flowers.
