### ISSUE TITLE
error: 'get_setting' was not declared in this scope

### ISSUE THREAD

**Issue by redblade7** [minetest/minetestmapper#63]
When attempting to compile 2018-03-25, I get:

> [  9%] Building CXX object CMakeFiles/minetestmapper.dir/db-postgresql.cpp.o
> (REMOVED)/minetestmapper-20180325/db-postgresql.cpp: In constructor 'DBPostgreSQL::DBPostgreSQL(const string&)':
> (REMOVED)/minetestmapper-20180325/db-postgresql.cpp:17:72: error: 'get_setting' was not declared in this scope
>   std::string const connect_string = get_setting("pgsql_connection", ifs);
>                                                                         ^
> CMakeFiles/minetestmapper.dir/build.make:278: recipe for target 'CMakeFiles/minetestmapper.dir/db-postgresql.cpp.o' failed
> make[2]: *** [CMakeFiles/minetestmapper.dir/db-postgresql.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/minetestmapper.dir/all' failed
> make[1]: *** [CMakeFiles/minetestmapper.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2

The previous version (2017-06-06) works fine.

**Comment by sfan5** [comment]
This was fixed but not put into a release (yet), please use git master instead.
