### ISSUE TITLE
Mapper producing white image for short vertical ranges

### ISSUE THREAD

**Issue by michael-ts** [minetest/minetestmapper#66]
I created a building with multiple levels and I'm trying to create images showing the floor plan for each level.  But it seems like when I specify the exact level of the floor it often returns a completely white image, e.g. `--min-y 44 --max-y 44`. 

The documentation says nodes won't be drawn *below* min-y or *above* max-y so min-y == max-y *should* work to slice out an exact floor plan at a specific level, but it only works sometimes, and when it does work it usually doesn't even get the correct y level but rather by luck (?) gets an adjacent level.

The actual number of y levels that work appears to be exactly 1 in 16 and is on multiple of 16 which suggests there is some issue with chunking.

I have the same problem when the vertical range is two high, except in this case I get white images in all but 2 of every 16 locations, where the max value modulus 16 is 0 or 1.  Likewise if the vertical range is three high all but 3 out of every 16 locations returns a white image, where the max value modulus 16 is 0, 1, or 2 and so forth.

This is problematic because my levels are less than 16 blocks high, making it impossible or difficult to map unless the floor just happens to be at the right range of moduluses.

**Comment by michael-ts** [comment]
@sfan5 is this fixed now?

**Comment by sfan5** [comment]
Yes.
