### ISSUE TITLE
Slow, possibly broken rendering if legacy entries are present in colors.txt

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetestmapper#7]
Megaf initially spotted the trigger for the long overview map rendering times he and I had been fighting with today:  If your colors.txt has the old legacy entries at the start of the file, i.e. stuff of the form:
```
xxx xxx xxx xxx #CONTENT_XXXXX
```
...the mapper will take a very long time (at least an hour for what should take 3-4 minutes) to produce an image, and what it produces may end up being nothing but an all-white image (perhaps with the scale at the side/top if --drawscale is specified).  Simply deleting those lines from the start of the file is sufficient to workaround the issue.

After working backward through the history, this commit appears to be the cause:  https://github.com/minetest/minetestmapper/commit/84d46ab8eb3205d47605817e390b529398a72ff5 

Before this commit, colors.txt with the legacy entries takes about as much time as one would expect.

**Comment by sfan5** [comment]
Rendering pre-0.4 maps with the current version probably doesn't work anyway.
Legacy entries don't need to be in anyones colors.txt anymore.
