### ISSUE TITLE
Lack of support for minetest versions earlier than 0.4.8

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetestmapper#76]
When trying to generate a map from minetest 0.4.7 world, I get an error `Exception: Setting 'backend' not found` as shown below.  Generating image from 0.4.8 world produces no such error.
```
juozas@xubuntu:~/minetestmapper$ ./minetestmapper -i ~/.minetest/worlds/0.4.7 -o ~/Darbastalis/0.4.7.png
Warning: Falling back to using colors.txt from current directory.
Exception: Setting 'backend' not found
```
P.s. the build compiled from 0.4.7 source doesn't have a world type (mapgen) choice when creating new world and generated map doesn't include all the information minetestmapper needs so map generation fails when using minetestmapper against that map, also old minetestmapper.py bundled with 0.4.7 source works but is painfully slow.

**Comment by rubenwardy** [comment]
Supporting versions that old is a misfeature, you should check out the version of this code from that time or update to the latest version. Minetest will do that automatically when loading a world

(You could also try setting backend in world.mt)

**Comment by sfan5** [comment]
Not sure I'd call it a misfeature, but you can pass `--backend sqlite3` to minetestmapper to make it work.

**Comment by Calinou** [comment]
I guess minetestmapper should fall back to the `sqlite3` backend if no `backend` setting is present in `world.mt`.
