### ISSUE TITLE
Unpin this repository, pin contentdb instead

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetestmapper#80]
This issue is only about GitHub …

This repository is one of the 3 pinned repositories of Minetest.
This means it appears on the top of <https://github.com/minetest>.

But the minetestmapper really is not THAT important. I consider the contentdb to be more important.

Please unpin the minetestmapper repo, and pin contentdb instead.

Thanks.

**Comment by sfan5** [comment]
While ContentDB is more important overall, I don't think users often need to look at its <i>source code</i> whereas you do need to look at this repo to make use of the mapper.

In any case, I can't change the pinned repos myself.
