### ISSUE TITLE
min/mix not working properly

### ISSUE THREAD

**Issue by basxto** [minetest/minetestmapper#84]
I try to get a map from mineclone2's The End with: `--min-y -6200  --max-y -6000`
But that only produces an empty map.
Only doing `--max-y -6000` works, but the nether shows through.

**Comment by sfan5** [comment]
Any messages in the log output?
Do you have sample map for me to test?

**Comment by basxto** [comment]
Since it's maybe a bit big, I temporarily uploaded it to my server:

[map.sqlite](https://basxto.de/mtmapper_mcl/)

[mcl2_colors_patched.txt](https://basxto.de/mtmapper_mcl/mcl2_colors_patched.txt)

The map database was created by my client.


```
$ minetestmapper -i ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/ -o ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/holarse_mc2_end.png --backend sqlite3 --colors ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/mcl2_colors_patched.txt --min-y -6200 --max-y -6000
'ailed to parse color entry '
```

But I get that error always, the the working version also has it:

```
$ minetestmapper -i ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/ -o ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/holarse_mc2_end.png --backend sqlite3 --colors ~/.minetest/worlds/server_gameserver.holarse-linuxgaming.de_30009/mcl2_colors_patched.txt --max-y -6000 
'ailed to parse color entry '
```

**Comment by sfan5** [comment]
I think you simply have your positions set wrong:
`--min-y -30000 --max-y -29000` renders the Nether here and `--min-y -28000 --max-y -27000` the End dimension

**Comment by sfan5** [comment]
Yep, confirmed it ingame.

**Comment by basxto** [comment]
Thanks a lot, I should've checked it ingame. 🤦

I apparently looked at the wrong (probably outdated) location within minclone2's code
