### ISSUE TITLE
Exception: unable to open database file

### ISSUE THREAD

**Issue by InFerYes** [minetest/minetestmapper#85]
Hi, I'm getting the following error:

```bash
./minetestmapper -i /var/lib/minetest/minetest-server/ -o map.png
Warning: Falling back to using colors.txt from current directory.
Exception: unable to open database file
```

I have tried disabling the server but it's the same issue. I have also tried `-i /var/lib/minetest/minetest-server/world.mt` but then it says `Exception: Failed to open world.mt`.

How can I fix this?

Minetest is 5.4.1.

**Comment by sfan5** [comment]
Is the database file readable by the user your are running under? You can check the permissions with `ls -l`.

**Comment by InFerYes** [comment]
I didn't know where the actual database was stored. The installation from the AUR has everything scattered in different folders. I have found the right folders now and managed to run the mapper tool.
