### ISSUE TITLE
Docs: Missing dependency: python3-pil (for use with generate_colorstxt.py script)

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetestmapper#89]
In addition to the dependencies mentioned in the README, i had to install `python3-pil` as a separate package.

Compiling the mapper went fine but running the `util/generate_colorstxt.py` script aborted early with an error message without that package.

**Comment by sfan5** [comment]
The script has a human-readable error message which mentions the package to install.
Putting it in the readme would be wrong because the actual mapper does not depend on PIL (or anything python).

**Comment by randomMesh** [comment]
Ok, makes sense.
