### ISSUE TITLE
Crash: terminate called after throwing an instance of 'ZlibDecompressor::DecompressError'

### ISSUE THREAD

**Issue by limburgher** [minetest/minetestmapper#91]
What can I provide to help diagnose? Using 2020-03-28 on Fedora 35, with a large map backed by Postgres.

**Comment by sfan5** [comment]
Probably just a corrupted block in your map. Try this and see if it renders fine otherwise:
```diff
diff --git a/TileGenerator.cpp b/TileGenerator.cpp
index 137eafe..be19edc 100644
--- a/TileGenerator.cpp
+++ b/TileGenerator.cpp
@@ -494,7 +494,13 @@ void TileGenerator::renderMap()
                        assert(pos.y >= m_yMin / 16 && pos.y < yMax);
 
                        blk.reset();
-                       blk.decode(it.second);
+                       try {
+                               blk.decode(it.second);
+                       } catch (const std::exception &e) {
+                               std::cerr << "Bad block " << pos.x << "," << pos.y << "," << pos.z
+                                       << ": " << e.what() << std::endl;
+                               continue;
+                       }
                        if (blk.isEmpty())
                                continue;
                        renderMapBlock(blk, pos);
```

**Comment by limburgher** [comment]
It still crashed. Assuming we can find the bad block, is it fixable?

**Comment by sfan5** [comment]
Nevermind that didn't work, try this:
```diff
diff --git a/TileGenerator.cpp b/TileGenerator.cpp
index 137eafe..b0d8bae 100644
--- a/TileGenerator.cpp
+++ b/TileGenerator.cpp
@@ -494,7 +494,12 @@ void TileGenerator::renderMap()
                        assert(pos.y >= m_yMin / 16 && pos.y < yMax);
 
                        blk.reset();
-                       blk.decode(it.second);
+                       try {
+                               blk.decode(it.second);
+                       } catch (...) {
+                               std::cerr << "Bad block " << pos.x << "," << pos.y << "," << pos.z << std::endl;
+                               continue;
+                       }
                        if (blk.isEmpty())
                                continue;
                        renderMapBlock(blk, pos);
```

**Comment by limburgher** [comment]
Ah, there we are. It's catching the exception, printing the bad block, and moving on.

How do I fix bad blocks?

**Comment by limburgher** [comment]
I ran minetestserver --rebuild over all 16041731 blocks, which didn't help.

**Comment by sfan5** [comment]
It's one of:
1. The blocks are fine and minetestmapper has a bug in which case that can be fixed
2. The block is actually corrupt, there's not much to do then. You can delete it from the db and hope it doesn't happen again.

I've just pushed a `--dumpblock` option, if you pass it the position of a bad block (as logged before) it will output a bunch of stuff and with that output I can take a closer look.

**Comment by limburgher** [comment]
Here's the output for -10,2,-623.
1d28b52ffd0058350100c800ffff0767b5aa000001000000036169720202000f000a000003100000d00bfffd8bff7b26

**Comment by limburgher** [comment]
I'm not sure what the in-game symptoms of a bad block might be, but it all looks fine from that perspective.

**Comment by sfan5** [comment]
I tested that locally and couldn't find anything wrong with it, minetestmapper renders it fine too (it's entirely empty).
Maybe something wrong with the postgres backend? Dunno.

Is it always the same block positions that throw an error? With how many does this happen?

**Comment by limburgher** [comment]
I got over 17 million unique bad block errors. But the map looks and behaves normally from inside. But this is capturing all exceptions as bad block, so there's that.

**Comment by sfan5** [comment]
After testing a bunch with with PostgreSQL locally I couldn't find anything that wasn't working perfectly.
Environment details (maybe these help _someone_ figure this out...):
<pre>
Arch Linux x86_64
Minetest 5.6.0-dev
PostgreSQL 13.5
zlib 1.2.11, zstd 1.5.2
</pre>


> I'm not sure what the in-game symptoms of a bad block might be, but it all looks fine from that perspective.

Btw if you want to check out the block in-game you need to multiply the coords by 16. The one from earlier would be at (-160, 32, -9968).

**Comment by limburgher** [comment]
I spot checked a few blocks in game and they look fine. Maybe it's a timeout issue? The box is doing other things, though I do have the recommended server settings from the minetest docs.

Fedora 35 x86_64
minetest 5.5.0
PostgreSQL 13.4
zlib 1.2.11
zstd 1.5.2

**Comment by demetera** [comment]
I have the same with Minetest 5.5.0 created worlds (minetest game and mineclone 2)
Managed to convert my old world successfully
(I don't remember exact version, but I've played September 2020)

**Comment by limburgher** [comment]
Is there anything one needs to do specifically to convert a world to the latest version, aside from playing it?

**Comment by sfan5** [comment]
MapBlocks that are loaded and written back during playtime are automatically upgraded to the newest format. You can also perform this operation in bulk on entire map using the `--recompress` flag of minetestserver.

**Comment by limburgher** [comment]
Running --recompress fixed everything. Mind you, it took awhile. :)
