### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by InFerYes** [minetest/minetestmapper#92]
Hi, i just compiled the latest release version minetestmapper 2022-02-21 and ended up with a white map due to a whole lot of item not being recognized. I changed my colors.txt file and rerun the command but keep getting the exact same output every time:

```
./minetestmapper -i /var/lib/minetest/minetest-server-backup/ -o map2.png
Warning: Falling back to using colors.txt from current directory.
Exception: database disk image is malformed        ] 29% 
```

**Comment by sfan5** [comment]
Are you sure the backup you have is valid? The `map.sqlite` file in particular.
minetestmapper doesn't do anything special.

**Comment by InFerYes** [comment]
I don't know what caused it, I still have that particular backup. In the meanwhile I have updated the mod and ran minetestmapper on the new backup (with updated mod files) and now it _does_ work everytime.

I'm guessing this is not a minetestmapper bug but a result from the sqlite reader?

**Comment by sfan5** [comment]
:shrug:
