### ISSUE TITLE
Map from latest Minetest (ZstdDecompressor::DecompressError)

### ISSUE THREAD

**Issue by Sharpik** [minetest/minetestmapper#95]
Hi,
can i ask someone here to help me to solve this error:

Platform: Windows 11
Map format: LevelDB
Minetest: Latest dev

Terminal error:
terminate called after throwing an instance of 'ZstdDecompressor::DecompressError'

Thanks

**Comment by Nazalassa** [comment]
I also got this error, but only with some subgames. Like, for Repixture and Asuna it doesn't work, whereas MTG and Exile (for example) don't cause the error.

**Comment by sfan5** [comment]
Need an example map to debug this.
