### ISSUE TITLE
`dumpnodes` crashes on deprecated tile field names

### ISSUE THREAD

**Issue by RodentOfUnusualSize** [minetest/minetestmapper#97]
Greetings, Earthlings!

I was attempting to use the mapper with a game using the [TechAge mod pack](https://content.minetest.net/packages/joe7575/techage_modpack/)—specifically, I was trying to generate the colour map with the `dumpnodes` mod—and… my game died a horrible, flaming death. :fire:

```
ServerError: AsyncErr: Lua: Runtime error from mod 'dumpnodes' in callback on_chat_message(): ...ria/snap/minetest/1828/.minetest/mods/dumpnodes/init.lua:48: attempt to concatenate local 'tex' (a nil value)
stack traceback:
	...ria/snap/minetest/1828/.minetest/mods/dumpnodes/init.lua:48: in function 'func'
	...inetest/1828/bin/../share/minetest/builtin/game/chat.lua:79: in function <...inetest/1828/bin/../share/minetest/builtin/game/chat.lua:52>
	...est/1828/bin/../share/minetest/builtin/game/register.lua:431: in function <...est/1828/bin/../share/minetest/builtin/game/register.lua:417>
```

After some time weeping despondently in the ashes of my lovely former minetest world, I decided to investigate. 🕵🏾‍♀️ I glared intensely at the mod’s code, willing it to reveal its secrets to me, and came upon the understanding that the `get_tile()` function was returning `nil` for the following TechAge nodes:

* `techage:axle_on`
* `techage:cooler`
* `techage:cooler_on`
* `techage:forceloadtile`
* `techage:gearbox_on`
* `techage:meltingpot_active`
* `techage:oilexplorer_on`
* `techage:ta2_autocrafter_act`
* `techage:ta2_distributor_act`
* `techage:ta2_gravelsieve_act`
* `techage:ta2_grinder_act`
* `techage:ta2_rinser_act`
* `techage:ta3_autocrafter_act`
* `techage:ta3_distributor_act`
* `techage:ta3_gravelsieve_act`
* `techage:ta3_grinder_act`
* `techage:ta3_rinser_act`
* `techage:ta4_autocrafter_act`
* `techage:ta4_collider_cooler`
* `techage:ta4_distributor_act`
* `techage:ta4_gravelsieve_act`
* `techage:ta4_grinder_act`
* `techage:ta4_high_performance_distributor_act`
* `techage:ta4_recycler_act`

Further vicious abuse of both mods led me to enlightenment. :microscope: These nodes appear to use a table tile definition, but do not have a `name` field. Instead, they have [the deprecated, but still supported, `image` field](https://minetest.gitlab.io/minetest/definition-tables/#tile-definition).

To test this theory, I applied arcane witchcraft 🧙🏾‍♀️, and modified the `get_tile()` as such:

```lua
local function get_tile(tiles, n)
	local tile = tiles[n]
	if type(tile) == 'table' then
		local name = tile.name
		if name == nil then
			name = tile.image
		end
		return name
	end
	return tile
end
```

With great trepidation I loaded my world with the modified mod… ran the `/dumpnodes` command… and… (dramatic pause)… success! 🦸🏾‍♀️

After sobering up from the raucous festivities celebrating this accomplishment, I paused to consider whether to provide a pull request with the fix for this issue. I decided, instead, to stay my hand, and leave you with just the issue for the now, because there may be no interest in providing support for a deprecated feature. (I will also inform the TechAge modpack maintainer about the deprecated field names.) On the other hand, a crash is a bad look.

Perhaps, instead of… or in addition to… providing support for the deprecated `image` field name in `get_tile()`, a check could be added to see if the return value is `nil`, and if so, the problematic node name could be logged, and maybe a fallback provided. At the end of the command, in addition to printing the number of nodes dumped, one could also print the number of nodes that were problems, if any.

I am not sure if you think how much extra weight is worth it for this simple utility mod, so I will wait for word from the powers that be before going any further. But if you like, I would be happy to fork, branch, fix, and pull request some changes to make `dumpnodes` a little hardier.

**Comment by sfan5** [comment]
I merged the proposed fix and set you as the proposed commit author, hope you don't mind.
Thanks for reporting.
